### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by GitHubBoys** [timoschick/pet#101]
Hi, AG's News error,Can you help me to see how to solve it？
```
 python3 cli.py \
--method pet \
--pattern_ids 0 1 2 3 4 5 \
--data_dir ../agnews-data \
--model_type roberta \
--model_name_or_path roberta-large \
--task_name agnews \
--output_dir agnews-output \
--do_train \
--do_eval \
--train_examples 10 \
--unlabeled_examples 40000 \
--split_examples_evenly \
--pet_per_gpu_train_batch_size 1 \
--pet_per_gpu_unlabeled_batch_size 3 \
--pet_gradient_accumulation_steps 4 \
--pet_max_steps 250 \
--lm_training \
--sc_per_gpu_train_batch_size 4 \
--sc_per_gpu_unlabeled_batch_size 4 \
--sc_gradient_accumulation_steps 4 \
--sc_max_steps 5000
```

```
2023-04-26 21:24:42,162 - INFO - cli - Parameters: Namespace(adam_epsilon=1e-08, alpha=0.9999, cache_dir='', data_dir='./agnews-data', decoding_strategy='default', do_eval=True, do_train=True, eval_set='dev', ipet_generations=3, ipet_logits_percentage=0.25, ipet_n_most_likely=-1, ipet_scale_factor=5, learning_rate=1e-05, lm_training=True, logging_steps=50, max_grad_norm=1.0, method='pet', model_name_or_path='./roberta-large', model_type='roberta', no_cuda=False, no_distillation=False, output_dir='./agnews-output', overwrite_output_dir=False, pattern_ids=[0, 1, 2, 3, 4, 5], pet_gradient_accumulation_steps=4, pet_max_seq_length=256, pet_max_steps=250, pet_num_train_epochs=3, pet_per_gpu_eval_batch_size=8, pet_per_gpu_train_batch_size=1, pet_per_gpu_unlabeled_batch_size=3, pet_repetitions=3, priming=False, reduction='wmean', sc_gradient_accumulation_steps=4, sc_max_seq_length=256, sc_max_steps=5000, sc_num_train_epochs=3, sc_per_gpu_eval_batch_size=8, sc_per_gpu_train_batch_size=4, sc_per_gpu_unlabeled_batch_size=4, sc_repetitions=1, seed=42, split_examples_evenly=True, task_name='agnews', temperature=2, test_examples=-1, train_examples=10, unlabeled_examples=40000, verbalizer_file=None, warmup_steps=0, weight_decay=0.01, wrapper_type='mlm')
2023-04-26 21:24:42,252 - INFO - tasks - Creating features from dataset file at ./agnews-data (num_examples_per_label=[3, 3, 2, 2], set_type=train)
2023-04-26 21:24:43,092 - INFO - tasks - Returning 10 train examples with label dist.: [('3', 2), ('4', 2), ('2', 3), ('1', 3)]
2023-04-26 21:24:43,092 - INFO - tasks - Creating features from dataset file at ./agnews-data (num_examples_per_label=-1, set_type=dev)
2023-04-26 21:24:43,140 - INFO - tasks - Returning 7600 dev examples with label dist.: [('3', 1900), ('4', 1900), ('2', 1900), ('1', 1900)]
2023-04-26 21:24:43,140 - INFO - tasks - Creating features from dataset file at ./agnews-data (num_examples=40000, set_type=unlabeled)
2023-04-26 21:24:43,991 - INFO - tasks - Returning 40000 unlabeled examples with label dist.: [('1', 40000)]
Traceback (most recent call last):
  File "cli.py", line 282, in <module>
    main()
  File "cli.py", line 263, in main
    no_distillation=args.no_distillation, seed=args.seed)
  File "/gpfs/home/chenzhiqiang_stu/pet-master/pet/modeling.py", line 249, in train_pet
    save_unlabeled_logits=not no_distillation, seed=seed)
  File "/gpfs/home/chenzhiqiang_stu/pet-master/pet/modeling.py", line 341, in train_pet_ensemble
    wrapper = init_model(model_config)
  File "/gpfs/home/chenzhiqiang_stu/pet-master/pet/modeling.py", line 146, in init_model
    model = TransformerModelWrapper(config)
  File "/gpfs/home/chenzhiqiang_stu/pet-master/pet/wrapper.py", line 151, in __init__
    cache_dir=config.cache_dir if config.cache_dir else None)  # type: PreTrainedTokenizer
  File "/gpfs/home/chenzhiqiang_stu/anaconda3/envs/torch3.6/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1787, in from_pretrained
    **kwargs,
  File "/gpfs/home/chenzhiqiang_stu/anaconda3/envs/torch3.6/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1915, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/gpfs/home/chenzhiqiang_stu/anaconda3/envs/torch3.6/lib/python3.6/site-packages/transformers/models/roberta/tokenization_roberta.py", line 228, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by GitHubBoys** [comment]
china net error, download token,then read
```
from transformers import AutoTokenizer
checkpoint = "./roberta-large"
tokenizer = AutoTokenizer.from_pretrained("roberta-large")
tokenizer.save_pretrained("./token")
```
<img width="176" alt="image" src="https://user-images.githubusercontent.com/15064119/234799449-a3416b4b-5cbf-4f69-93a9-4772192750f1.png">
