### ISSUE TITLE
Training PET on a personalised task

### ISSUE THREAD

**Issue by xruifan** [timoschick/pet#78]
Hi, I am trying to train PET on a new task. I have edited `custom_task_processor.py` and `custom_task_pvp.py` in /examples for my use. So my question is how could I use them to make the program run them before I call `cli.py` with `--task_name my-task`. I have seen people saying copying the classes directly to the respective files but is it a formal way to do that? 

Thanks.

**Comment by chris-aeviator** [comment]
I have in the past also copied it into the `tasks.py` file and approached (yday) to make it better.

When importing the class from the examples dir, rather than adding it directly to `tasks.py`, I'm facing a circular import error, to be expected, since `custom_task_processor.py` itself also imports `tasks.py`. Will share my findings here but also happy if s.o. could just provide a better instruction

**Comment by argjendhaxhiu** [comment]
@chris-aeviator I tried your suggestion but when I commented out 

from pet.tasks import DataProcessor, PROCESSORS, TASK_HELPERS
PROCESSORS[MyTaskDataProcessor.TASK_NAME] = MyTaskDataProcessor


I get the error:

2023-09-24 22:29:49,211 - INFO - tasks - Creating features from dataset file at custom_task/dataset (num_examples=-1, set_type=unlabeled)
2023-09-24 22:29:49,212 - INFO - tasks - Returning 2 unlabeled examples with label dist.: [('0', 2)]
Traceback (most recent call last):
  File "cli.py", line 282, in <module>
    main()
  File "cli.py", line 258, in main
    pet.train_pet(pet_model_cfg, pet_train_cfg, pet_eval_cfg, sc_model_cfg, sc_train_cfg, sc_eval_cfg,
  File "/pet/pet/modeling.py", line 246, in train_pet
    train_pet_ensemble(ensemble_model_config, ensemble_train_config, ensemble_eval_config, pattern_ids, output_dir,
  File "/pet/pet/modeling.py", line 341, in train_pet_ensemble
    wrapper = init_model(model_config)
  File "/pet/pet/modeling.py", line 146, in init_model
    model = TransformerModelWrapper(config)
  File "/pet/pet/wrapper.py", line 169, in __init__
    self.preprocessor = PREPROCESSORS[self.config.wrapper_type](self, self.config.task_name, self.config.pattern_id,
  File "/pet/pet/preprocessor.py", line 38, in __init__
    self.pvp = PVPS[task_name](self.wrapper, pattern_id, verbalizer_file)  # type: PVP
KeyError: 'my-task'

Do you have any idea what's going wrong?
